name: Go

on:
  push:
    branches:
      - Go-Ver

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: amd64
            goos: windows
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go get .
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }} 
      - name: Build
        run: go build
