name: Go

on:
  push:
    branches:
      - Go-Ver

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23.1']
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: amd64
            goos: windows
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: go build -v ./...
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }} 
          CGO_ENABLED: 0
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: KinhWeb.Go-${{ matrix.goos }}-${{ matrix.goarch }}
